spring.application.name=springboot-tomcat-demo

server.servlet.context-path=/springboot-tomcat-demo

app.environment=local
app.message=Spring Boot deployed successfully on External Tomcat!

logging.level.root=INFO
logging.level.com.demo=INFO
