spring.application.name=springboot-tomcat-demo

server.servlet.context-path=/springboot-tomcat-demo

management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always

management.info.env.enabled=true

info.app.name=${spring.application.name}
info.app.description=Spring Boot application for DevOps learning
info.app.version=1.1.0
